name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Set up permissions
        run: chmod +x ./build.sh
      - name: creates output
        run: ./build.sh
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: AUTO_ACTIONS
        with:
          source-directory: 'output'
          destination-github-username: 'wh0land'
          destination-repository-name: 'madadoc'
          user-email: EMAIL
          target-branch: master
